### ISSUE TITLE
Move plantuml to peerDependencies

### ISSUE THREAD

**Issue by cezaryrk** [krlwlfrt/omeco#2]
Not everybody has java installed, move the plantuml dependency to devDeps and add to peerDeps.

**Comment by cezaryrk** [comment]
How long does this take?

**Comment by cezaryrk** [comment]
waiting ....

**Comment by cezaryrk** [comment]
is someone here?

**Comment by cezaryrk** [comment]
hallo ... issue is wating!!!

**Comment by cezaryrk** [comment]
ready?

**Comment by krlwlfrt** [comment]
Included in v0.13.0.
